### ISSUE TITLE
Never encountered error in cyto_gate_draw

### ISSUE THREAD

**Issue by northNomad** [DillonHammill/CytoExploreR#85]
Hi,

Thanks for taking the time to review this issue -

My lab recently acquired a new cytoflex machine and I'm having some problems analyzing my data using my scripts.

When I draw my gate 
```
fs <- read.flowset(path = "./fcs", pattern = ".fcs", transformation = F, alter.names = T)
gs <- GatingSet(fs)

lgcl.obj <- logicle_trans()
lgcl.tlist <- transformerList(colnames(gs)[5:12], lgcl.obj)
transform(gs, lgcl.tlist)
```
```
cyto_gate_draw(gs,
               channels = c("FSC.A", "SSC.A"),
               parent = "root",
               alias = "lymph",
               gatingTemplate = "primary_samples.csv"
               )
```

I'm getting the following error:

```
Error in .local(x, i, j, ...) : 
  subscript out of bounds (index must have length 1 and be positive)
```

Any insight would be great!

**Comment by DillonHammill** [comment]
@northNomad, if you send through the output of `traceback()` after encountering an error, it will help me to troubleshoot this.

**Comment by northNomad** [comment]
> @northNomad, if you send through the output of `traceback()` after encountering an error and `sessionInfo()` it will help me to troubleshoot this.

Appreciate the prompt response as always Dillon!
Thanks so much for real.

```
> traceback()
16: stop("subscript out of bounds (index must have length 1 and be positive)")
15: .local(x, i, j, ...)
14: x[[n]]
13: x[[n]]
12: FUN(X[[i]], ...)
11: lapply(sampleNames(x), function(n) {
        y <- x[[n]]
        FUN(if (use.exprs) 
            exprs(y)
        else y, ...)
    })
10: structure(lapply(sampleNames(x), function(n) {
        y <- x[[n]]
        FUN(if (use.exprs) 
            exprs(y)
        else y, ...)
    }), names = sampleNames(x))
9: .nextMethod(x = x, FUN = FUN)
8: callNextMethod()
7: fsApply(x, function(fr) {
       ind <- match(cyto_names(fr), nms)
       mat <- matrix(rep(ind, .cyto_count(fr)), ncol = 1)
       colnames(mat) <- "Sample ID"
       suppressWarnings(fr_append_cols(fr, mat))
   })
6: fsApply(x, function(fr) {
       ind <- match(cyto_names(fr), nms)
       mat <- matrix(rep(ind, .cyto_count(fr)), ncol = 1)
       colnames(mat) <- "Sample ID"
       suppressWarnings(fr_append_cols(fr, mat))
   })
5: cyto_barcode(x, ...)
4: cyto_merge_by.flowSet(fs, merge_by = group_by, select = select)
3: cyto_merge_by(fs, merge_by = group_by, select = select)
2: cyto_gate_draw.GatingSet(gs, channels = c("FSC.H", "SSC.H"), 
       parent = "root", alias = "lymph", gatingTemplate = "primary_samples.csv", 
       ylim = c(0, 1e+06))
1: cyto_gate_draw(gs, channels = c("FSC.H", "SSC.H"), parent = "root", 
       alias = "lymph", gatingTemplate = "primary_samples.csv", 
       ylim = c(0, 1e+06))
```

**Comment by DillonHammill** [comment]
Looks like another cytoframe issue. I have fixed this on the `devel` branch which will be merged to `master` soon. If I don't get to finish everything over the weekend I will push the fix to `master` for you.

**Comment by northNomad** [comment]
> Looks like another cytoframe issue. I have fixed this on the `devel` branch which will be merged to `master` soon. If I don't get to finish everything over the weekend I will push the fix to `master` for you.

Appreciate your effort a lot -

**Comment by DillonHammill** [comment]
@northNomad, I actually just pushed the fix to the `master` branch for you. Please pull down the latest version of CytoExploreR and give it a try:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by northNomad** [comment]
> @northNomad, I actually just pushed the fix to the `master` branch for you. Please pull down the latest version of CytoExploreR and give it a try:
> 
> ```
> devtools::install_github("DillonHammill/CytoExploreR")
> ```

Hmm, I've successfully updated the package but the error remains.

Here is the console with
- Install
- setup cyto
- error thrown
- warnings()
- traceback()
- sessioninfo

```
** testing if installed package keeps a record of temporary installation path
* DONE (CytoExploreR)
> 
> wd <- dirname(rstudioapi::getSourceEditorContext()$path)
> setwd(wd)
> library(tidyverse)
-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
v ggplot2 3.3.2     v purrr   0.3.4
v tibble  3.0.3     v dplyr   1.0.0
v tidyr   1.1.0     v stringr 1.4.0
v readr   1.3.1     v forcats 0.5.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
Warning messages:
1: package ‘tidyverse’ was built under R version 4.0.2 
2: package ‘ggplot2’ was built under R version 4.0.2 
3: package ‘tibble’ was built under R version 4.0.2 
4: package ‘tidyr’ was built under R version 4.0.2 
5: package ‘readr’ was built under R version 4.0.2 
6: package ‘purrr’ was built under R version 4.0.2 
7: package ‘dplyr’ was built under R version 4.0.2 
8: package ‘stringr’ was built under R version 4.0.2 
9: package ‘forcats’ was built under R version 4.0.2 
> library(CytoExploreR)
Loading required package: flowCore
Loading required package: flowWorkspace
As part of improvements to flowWorkspace, some behavior of
GatingSet objects has changed. For details, please read the section
titled "The cytoframe and cytoset classes" in the package vignette:

  vignette("flowWorkspace-Introduction", "flowWorkspace")
Loading required package: openCyto
> library(viridis)
Loading required package: viridisLite
Warning messages:
1: package ‘viridis’ was built under R version 4.0.2 
2: package ‘viridisLite’ was built under R version 4.0.2 
> library(ggpubr)
Warning message:
package ‘ggpubr’ was built under R version 4.0.2 
> 
> fs <- read.flowSet(path = "./Exp_20200828_8/",
+                    pattern = ".fcs",
+                    alter.names = T, 
+                    transformation = F)
There were 50 or more warnings (use warnings() to see the first 50)
> gs <- GatingSet(fs)
> 
> lgcl.obj <- logicle_trans()
> lgcl.tlist <- transformerList(colnames(gs)[5:12], lgcl.obj)
> transform(gs, lgcl.tlist)
A GatingSet with 49 samples
> 
> gs <- cyto_names_parse(gs,
+                  vars = c("null", "day", "sample", "tr1", "tr2", "rep"),
+                  split = "_"
+                  )
> 
> #sytoxG FITC
> #CD14 PE
> #CD15 pecy7
> #CD11b APC
> 
> #cyto_gatingTemplate_create("primary_samples.csv")
> cyto_gate_draw(gs,
+                channels = c("FSC.H", "SSC.H"),
+                parent = "root",
+                alias = "lymph",
+                gatingTemplate = "primary_samples.csv"
+                
+                )
Error in .local(x, i, j, ...) : 
  subscript out of bounds (index must have length 1 and be positive)
> warnings()
Warning messages:
1: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
2: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
3: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL2.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
4: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL4.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
5: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
6: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FSC.Width' channel exceed its $PnR value 10000 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
7: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
8: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
9: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL4.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
10: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
11: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FSC.Width' channel exceed its $PnR value 10000 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
12: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
13: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
14: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
15: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
16: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
17: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
18: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL2.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
19: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
20: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
21: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
22: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
23: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
24: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
25: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL4.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
26: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
27: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
28: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
29: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
30: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
31: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL4.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
32: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
33: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
34: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
35: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
36: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
37: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
38: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL2.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
39: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
40: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FSC.Width' channel exceed its $PnR value 10000 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
41: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
42: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL2.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
43: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL4.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
44: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
45: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FSC.Width' channel exceed its $PnR value 10000 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
46: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
47: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL5.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
48: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'SSC.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
49: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL2.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
50: In readFCSdata(con, offsets, txt, transformation, which.lines,  ... :
  Some data values of 'FL4.A' channel exceed its $PnR value 8388607 and will be truncated!
 To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'
> traceback()
16: stop("subscript out of bounds (index must have length 1 and be positive)")
15: .local(x, i, j, ...)
14: x[[n]]
13: x[[n]]
12: FUN(X[[i]], ...)
11: lapply(sampleNames(x), function(n) {
        y <- x[[n]]
        FUN(if (use.exprs) 
            exprs(y)
        else y, ...)
    })
10: structure(lapply(sampleNames(x), function(n) {
        y <- x[[n]]
        FUN(if (use.exprs) 
            exprs(y)
        else y, ...)
    }), names = sampleNames(x))
9: .nextMethod(x = x, FUN = FUN)
8: callNextMethod()
7: fsApply(x, function(fr) {
       ind <- match(cyto_names(fr), nms)
       mat <- matrix(rep(ind, .cyto_count(fr)), ncol = 1)
       colnames(mat) <- "Sample ID"
       if (is(fr, "flowFrame")) {
           suppressWarnings(fr_append_cols(fr, mat))
       }
       else {
           suppressWarnings(cf_append_cols(fr, mat))
       }
   })
6: fsApply(x, function(fr) {
       ind <- match(cyto_names(fr), nms)
       mat <- matrix(rep(ind, .cyto_count(fr)), ncol = 1)
       colnames(mat) <- "Sample ID"
       if (is(fr, "flowFrame")) {
           suppressWarnings(fr_append_cols(fr, mat))
       }
       else {
           suppressWarnings(cf_append_cols(fr, mat))
       }
   })
5: cyto_barcode(x, ...)
4: cyto_merge_by.flowSet(fs, merge_by = group_by, select = select)
3: cyto_merge_by(fs, merge_by = group_by, select = select)
2: cyto_gate_draw.GatingSet(gs, channels = c("FSC.H", "SSC.H"), 
       parent = "root", alias = "lymph", gatingTemplate = "primary_samples.csv")
1: cyto_gate_draw(gs, channels = c("FSC.H", "SSC.H"), parent = "root", 
       alias = "lymph", gatingTemplate = "primary_samples.csv")
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    
system code page: 950

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggpubr_0.4.0        viridis_0.5.1       viridisLite_0.3.0   CytoExploreR_1.0.8  openCyto_2.0.0      flowWorkspace_4.0.6
 [7] flowCore_2.0.1      forcats_0.5.0       stringr_1.4.0       dplyr_1.0.0         purrr_0.3.4         readr_1.3.1        
[13] tidyr_1.1.0         tibble_3.0.3        ggplot2_3.3.2       tidyverse_1.3.0    

loaded via a namespace (and not attached):
  [1] readxl_1.3.1        changepoint_2.2.2   backports_1.1.7     plyr_1.8.6          splines_4.0.0      
  [6] fda_5.1.5.1         usethis_1.6.1       digest_0.6.25       htmltools_0.5.0     fansi_0.4.1        
 [11] magrittr_1.5        memoise_1.1.0       cluster_2.1.0       ks_1.11.7           openxlsx_4.1.5     
 [16] remotes_2.2.0       modelr_0.1.8        RcppParallel_5.0.2  matrixStats_0.56.0  R.utils_2.9.2      
 [21] askpass_1.1         cytolib_2.0.3       prettyunits_1.1.1   jpeg_0.1-8.1        colorspace_1.4-1   
 [26] blob_1.2.1          rvest_0.3.6         rrcov_1.5-5         haven_2.3.1         xfun_0.16          
 [31] callr_3.4.3         crayon_1.3.4        jsonlite_1.7.0      hexbin_1.28.1       graph_1.66.0       
 [36] zoo_1.8-8           glue_1.4.2          flowClust_3.26.0    gtable_0.3.0        zlibbioc_1.34.0    
 [41] car_3.0-9           pkgbuild_1.1.0      IDPmisc_1.1.20      Rgraphviz_2.32.0    BiocGenerics_0.34.0
 [46] DEoptimR_1.0-8      abind_1.4-5         scales_1.1.1        mvtnorm_1.1-1       DBI_1.1.0          
 [51] rstatix_0.6.0       Rcpp_1.0.5          xtable_1.8-4        tmvnsim_1.0-2       clue_0.3-57        
 [56] reticulate_1.16     foreign_0.8-80      rsvd_1.0.3          mclust_5.4.6        umap_0.2.6.0       
 [61] stats4_4.0.0        htmlwidgets_1.5.1   httr_1.4.2          RColorBrewer_1.1-2  ellipsis_0.3.1     
 [66] pkgconfig_2.0.3     XML_3.99-0.5        R.methodsS3_1.8.0   flowViz_1.52.0      dbplyr_1.4.4       
 [71] later_1.1.0.1       flowStats_4.0.0     tidyselect_1.1.0    rlang_0.4.7         reshape2_1.4.4     
 [76] visNetwork_2.0.9    munsell_0.5.0       cellranger_1.1.0    tools_4.0.0         cli_2.0.2          
 [81] generics_0.0.2      devtools_2.3.1      broom_0.7.0         fastmap_1.0.1       evaluate_0.14      
 [86] processx_3.4.3      knitr_1.29          fs_1.4.2            zip_2.1.0           EmbedSOM_2.1.1     
 [91] robustbase_0.93-6   RBGL_1.64.0         mime_0.9            rhandsontable_0.3.7 R.oo_1.23.0        
 [96] xml2_1.3.2          shinythemes_1.1.2   compiler_4.0.0      rstudioapi_0.11     curl_4.3           
[101] png_0.1-7           ggsignif_0.6.0      testthat_2.3.2      reprex_0.3.0        pcaPP_1.9-73       
[106] stringi_1.4.6       ps_1.3.4            RSpectra_0.16-0     desc_1.2.0          lattice_0.20-41    
[111] Matrix_1.2-18       vctrs_0.3.1         pillar_1.4.6        lifecycle_0.2.0     flowAI_1.18.5      
[116] data.table_1.13.0   corpcor_1.6.9       httpuv_1.5.4        R6_2.4.1            latticeExtra_0.6-29
[121] promises_1.1.1      rio_0.5.16          gridExtra_2.3       KernSmooth_2.23-17  RProtoBufLib_2.0.0 
[126] sessioninfo_1.1.1   MASS_7.3-51.6       gtools_3.8.2        assertthat_0.2.1    pkgload_1.1.0      
[131] openssl_1.4.2       rprojroot_1.3-2     withr_2.2.0         mnormt_2.0.1        parallel_4.0.0     
[136] hms_0.5.3           ncdfFlow_2.34.0     grid_4.0.0          rmarkdown_2.3       carData_3.0-4      
[141] Rtsne_0.15          Biobase_2.48.0      shiny_1.5.0         lubridate_1.7.9     ellipse_0.4.2     
```

**Comment by DillonHammill** [comment]
Looks like an issue with the actual fcs files. I have seen similar errors in recent flowCore/flowWorkspace issues - I am sure there is a solution there. `read.fliwSet` is now a legacy API, I would switch to using `cyto_setup()` instead. Also the `cyto_tranform()` and `cyto_transformer_()` functions have some benefits so I would switch to those as well.

**Comment by northNomad** [comment]
> Looks like an issue with the actual fcs files. I have seen similar errors in recent flowCore/flowWorkspace issues - I am sure there is a solution there. `read.fliwSet` is now a legacy API, I would switch to using `cyto_setup()` instead. Also the `cyto_tranform()` and `cyto_transformer_()` functions have some benefits so I would switch to those as well.

Ok, sounds good!
Actually, I see the same error when I try to call ```cyto_setup```

```
> gs <- cyto_setup(path = "fcs/")
Loading FCS files into a GatingSet...
Assigning markers to channels...
Loading required package: shiny
Warning: package ‘shiny’ was built under R version 4.0.2
Error in .local(x, i, j, ...) : 
  subscript out of bounds (index must have length 1 and be positive)
```
Must be issues with the .fcs i guess...

**Comment by northNomad** [comment]
@DillonHammill Could you please elaborate on the subscript out of bound error here?

Correct me if I'm wrong, but ```cyto_setup``` calls ```cyto_load```

If I call ```cyto_load```, I fail at the subsequent ```cyto_transform``` call
```
> gs <- cyto_load(path = "fcs/")
> gs <- cyto_transform(gs, type = "logicle")
Automatically transforming flowFrame/flowSet objects is not recommended as transformation definitions will be lost.
Error in .local(x, i, j, ...) : 
  subscript out of bounds (index must have length 1 and be positive)
```

If I call ```cyto_setup```, I straight-up fail
```
> gs <- cyto_setup(path = "fcs/")
Loading FCS files into a GatingSet...
Assigning markers to channels...
Experiment-Markers.csv found in working directory.
Error in .local(x, i, j, ...) : 
  subscript out of bounds (index must have length 1 and be positive)

```

**Comment by DillonHammill** [comment]
`cyto_load()` will read in the files to a `cytoset`. `cyto_setup()` will do other things for you as well, such as adding the `cytoset` to a `GatingSet`. The output of `cyto_load()` will therefore be a `cytoset` in your case. I think the errir you are seeing is due to the FCS files having data outside the PnR range. You could try the following as the warnings sugguest:
```{r}
gs <- cyto_load(path = "fcs/", truncate_max_range = FALSE)
```

If that doesn't work I will need you to send some FCS files to troubleshoot this.

**Comment by northNomad** [comment]
> `cyto_load()` will read in the files to a `cytoset`. `cyto_setup()` will do other things for you as well, such as adding the `cytoset` to a `GatingSet`. The output of `cyto_load()` will therefore be a `cytoset` in your case. I think the error you are seeing is due to the FCS files having data outside the PnR range. You could try the following as the warnings sugguest:
> 
> ```
> gs <- cyto_load(path = "fcs/", truncate_max_range = FALSE)
> ```
> 
> If that doesn't work I will need you to send some FCS files to troubleshoot this.

Saw that in one of the flowCore issue but unfortunately does not fix the problem.

```
> gs <- cyto_load(path = "fcs/", truncate_max_range = FALSE)
> cyto_transform(gs, type = "logicle")
Automatically transforming flowFrame/flowSet objects is not recommended as transformation definitions will be lost.
Error in .local(x, i, j, ...) : 
  subscript out of bounds (index must have length 1 and be positive)
```
attached is .zip with facs files
[fcs.zip](https://github.com/DillonHammill/CytoExploreR/files/5144837/fcs.zip)

**Comment by DillonHammill** [comment]
Thanks I just updated my previous comment. I will look at this within the next hour.

**Comment by DillonHammill** [comment]
Ok, so I picked up a couple of issues. The first is that replacing the `colnames()` of cytosets does not seem to be working - however it does work for cytoframes. The second is that coercion (merging) of a cytoset into a cytoframe/flowFrame using the `as` approach is also not working. I will have to check if there are new methods for these or whether they are simply not working. The first issue can be bypassed by setting `markers = FALSE` in `cyto_setup()` but the second cannot be bypassed because the coercion is used throughout CytoExploreR. I will file an issue with the cytoverse team and see if we can get this fixed soon. In the meantime I will hunt do any `colnames()` assignments and `fsApply()` calls and fix them. I will let you know once everything is working as expected - unfortunately you may have to wait until I merge the `devel` branch. I will do my best to get this ready early next week.

**Comment by DillonHammill** [comment]
Good news! I figured out that the problem was due to your filenames starting with an underscore. If you read your samples using `cyto_load()` and then fix the sample names before doing anything else, you should be good to go:
```{r}
cs <- cyto_load("fcs")
sampleNames(cs) <- gsub("^_", "", sampleNames(cs)) # fix sample names
cs_trans <- cyto_transform(cs) # works
```
I will push a fix for `colnames()` issue that you can use `cyto_setup()` too. As the message says it is not recommended to transform cytosets directly as they do not retain the transformation information that is used by `cyto_plot()`. Instead, it is better to load the data into a GatingSet` using `cyto_setup()` and then transform the GatingSet - you will notice the difference when plotting transformed parameters in `cyto_plot()`.

**Comment by northNomad** [comment]
@DillonHammill 

Very great news to wake up to!

Anecdote and side rant:

The BD-accuri cytometer that I used to work with prefixes each .fcs file with the well number ```A02, A03... etc```, so I always start my file name with an underscore to make my life with ```cyto_names_parse``` easier.
But the cytoflex does prefix my file so I ended up with a file name with an ```_``` to start.

Don't know if this is considered a bug or what.

Anyhow, thank you so much again.
Your efficiency never ceases to amaze me.

**Comment by northNomad** [comment]
> Good news! I figured out that the problem was due to your filenames starting with an underscore. If you read your samples using `cyto_load()` and then fix the sample names before doing anything else, you should be good to go:
> 
> ```
> cs <- cyto_load("fcs")
> sampleNames(cs) <- gsub("^_", "", sampleNames(cs)) # fix sample names
> cs_trans <- cyto_transform(cs) # works
> ```
> 
> I will push a fix for `colnames()` issue tomorrow so that you can use `cyto_setup()` too. As the message says it is not recommended to transform cytosets directly as they do not retain the transformation information that is used by `cyto_plot()`. Instead, it is better to load the data into a GatingSet using `cyto_setup()` and then transform the GatingSet - you will notice the difference when plotting transformed parameters in `cyto_plot()`.

I gave it a try, and the previous error has been solved.
Instead, it now throws an subset out of bounds error.

```
> cyto_gate_draw(gs,
+                channels = c("FSC-A", "SSC-A"),
+                parent = "root",
+                alias = "lymph",
+                gatingTemplate = "primary_samples.csv"
+                )
```

```
> traceback()
10: stop("Subset out of bounds", call. = FALSE)
9: x[ind]
8: x[ind]
7: FUN(X[[i]], ...)
6: lapply(seq_len(length(pd_split)), function(z) {
       ind <- match(pd_split[[z]][, "name"], cyto_names(x))
       x[ind]
   })
5: cyto_group_by(x, group_by = merge_by)
4: cyto_merge_by.flowSet(fs, merge_by = group_by, select = select)
3: cyto_merge_by(fs, merge_by = group_by, select = select)
2: cyto_gate_draw.GatingSet(gs, channels = c("FSC-A", "SSC-A"), 
       parent = "root", alias = "lymph", gatingTemplate = "primary_samples.csv")
1: cyto_gate_draw(gs, channels = c("FSC-A", "SSC-A"), parent = "root", 
       alias = "lymph", gatingTemplate = "primary_samples.csv")
```

**Comment by DillonHammill** [comment]
@northNomad, this is because the `identifiers` are changed when updating the `sampleNames`. The following should do the trick:
```{r}
cs <- cyto_load("fcs")
sampleNames(cs) <- gsub("^_", "", sampleNames(cs)) # fix sample names
cyto_names(cs) <- sampleNames(cs)
cs_trans <- cyto_transform(cs) # works
```
Do these files have the original names from the machine, or have you manually edited them? Renaming the files manually is not recommended as it does not update the associated `keywords` contained in the FCS files. Our lab has encountered similar naming issues on our machines, so I have written a function to fix this - it is not currently incorporated into CytoExploreR but perhaps I can add it as a new `cyto_names_strip()` API. This will allow you to remove the first or last fragment from the file name if required - the rest of name will need to be uniquely identifiable.

**Comment by DillonHammill** [comment]
@northNomad, a fix was just pushed to `flowWorkspace` to fix this issue for you. Please update your `flowWorkspace` and try again:
```{r}
devtools::install_github("RGLab/flowWorkspace")
```
Note that you should not need to manually fix the file names now, they should work as is (i.e. with the leading underscore).

**Comment by DillonHammill** [comment]
@northNomad, I also pushed a fix to CytoExploreR to resolve your `cyto_setup()` issue. Please pull down the latest CytoExploreR as well and give `cyto_setup()` another try:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by northNomad** [comment]
I am having trouble pulling the github version of flowWorkspace; it's having non-zero exit status.

I will update you as soon as I get this fixed.

**Comment by SgtVil** [comment]
Hello @DillonHammill , 
I encountered the same error with filenames such as 001(1).fcs, renaming them fixed the problem.
For those who would like to correct that kind of problem : 

`> files= list.files(path, pattern = ".fcs")`
`> for(f in files[which(str_detect(files,  "(?=\\().*?(?<=\\))"))]){  

file.rename(f, to= str_replace(pattern = "(?=\\().*?(?<=\\))", replacement = "_1", string =  f))
}
`
Of course the regex need to be modified to fit the expression. 

My files are coming from a cytoflex from Beckman Coulter, the (1) is given for a sample  with the same name that is repeated between multiple plates. To avoid these names a concatener is very welcome in the .csv (ex: 01-001-France_cohorte-isotype-A1.fcs)
